### ISSUE TITLE
EOF inesperado mientras se buscaba un «"» coincidente

### ISSUE THREAD

**Issue by AstralCam** [SupDroidStudio/mcpe-linux#1]
Hey, in the file _mcpe-linux-setup.sh_, line 68,  has an extra "

`68 | echo "To uninstall Minecraft, simply run the uninstall script as root [sudo].""  <- here`

**Comment by SupDroidStudio** [comment]
Thank you. This has been fixed in the latest version 2.2 - "Meerkat".
